// Mocks generated by Mockito 5.0.7 from annotations
// in brigadier_dart/test/command_dispatcher/command_dispatcher_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeType extends _i1.Fake implements Type {}

/// A class which mocks [Object].
///
/// See the documentation for Mockito's code generation for more information.
class MockObject extends _i1.Mock implements Object {
  MockObject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get hashCode => 0;
  @override
  Type get runtimeType => MockObject;
  @override
  bool operator ==(Object? other) {
    if (!(other is MockObject)) return false;

    return true;
  }
  @override
  String toString() => 'Object';
}
