// Mocks generated by Mockito 5.0.7 from annotations
// in brigadier_dart/test/exceptions/simple_command_syntax_exception_type/simple_command_syntax_exception_type_test.dart.
// Do not manually edit this file.

import 'package:brigadier_dart/src/exceptions/command_exception_type.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [CommandExceptionType].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandExceptionType extends _i1.Mock
    implements _i2.CommandExceptionType {
  MockCommandExceptionType() {
    _i1.throwOnMissingStub(this);
  }
}
