// Mocks generated by Mockito 5.0.7 from annotations
// in brigadier_dart/test/commad_dispatcher_usages/command_dispatcher_usages_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeType extends _i1.Fake implements Type {}

/// A class which mocks [Object].
///
/// See the documentation for Mockito's code generation for more information.
class MockObject extends _i1.Mock implements Object {
  MockObject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get hashCode =>
      (super.noSuchMethod(Invocation.getter(#hashCode), returnValue: 0) as int);
  @override
  Type get runtimeType => (super.noSuchMethod(Invocation.getter(#runtimeType),
      returnValue: _FakeType()) as Type);
  @override
  bool operator ==(Object? other) =>
      (super.noSuchMethod(Invocation.method(#==, [other]), returnValue: false)
          as bool);
  @override
  String toString() =>
      (super.noSuchMethod(Invocation.method(#toString, []), returnValue: '')
          as String);
}
